In [1]:
#Importing all necessary libraries for this model 

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
import pandas as pd
import os, requests, cv2, random
import math

from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing import image
from tensorflow.keras import models
from tensorflow.keras import Sequential, layers

from keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import confusion_matrix,classification_report

In [124]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras import backend as K

# Load the model
model = load_model("C:\\Users\\Niranjan\\Documents\\Data mining\\archive (1)\\cnn.h5")

# Choose the layer index you want to visualize
layer_index = 0

# Change this to the index of the layer you want to visualize

# Load the image and preprocess it
img_path = "C:\\Users\\Niranjan\\Documents\\Data mining\\archive (1)\\tomato\\101.JPG"
img = image.load_img(img_path, target_size=(224, 224))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.0

# Function to get the output of an intermediate layer
get_layer_output = K.function([model.layers[0].input], [model.layers[layer_index].output])
layer_output = get_layer_output([img_array])[0]
print(img_array*)
# Display the output of the intermediate layer
#plt.figure(figsize=(10, 5))
#plt.imshow(layer_output[0, :, :, 6], cmap='viridis')  # Adjust the channel index if needed
#plt.title(f'Output of Layer {layer_index}')
#plt.show()


[[[[0.37254903 0.37254903 0.38039216]
   [0.3764706  0.3764706  0.38431373]
   [0.37254903 0.37254903 0.38039216]
   ...
   [0.52156866 0.5294118  0.5254902 ]
   [0.5254902  0.53333336 0.5294118 ]
   [0.5254902  0.53333336 0.5294118 ]]

  [[0.3882353  0.3882353  0.39607844]
   [0.3882353  0.3882353  0.39607844]
   [0.38431373 0.38431373 0.39215687]
   ...
   [0.52156866 0.5294118  0.5254902 ]
   [0.5176471  0.5254902  0.52156866]
   [0.5058824  0.5137255  0.50980395]]

  [[0.39215687 0.39215687 0.4       ]
   [0.3882353  0.3882353  0.39607844]
   [0.38431373 0.38431373 0.39215687]
   ...
   [0.5254902  0.53333336 0.5294118 ]
   [0.52156866 0.5294118  0.5254902 ]
   [0.50980395 0.5176471  0.5137255 ]]

  ...

  [[0.3764706  0.37254903 0.3529412 ]
   [0.3647059  0.36078432 0.34117648]
   [0.3529412  0.34901962 0.32941177]
   ...
   [0.5058824  0.5058824  0.49803922]
   [0.5058824  0.5058824  0.49803922]
   [0.5058824  0.5058824  0.49803922]]

  [[0.37254903 0.36862746 0.34901962]
   [0.3